CountMoney_model:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('WAREHOUSE_HOST') }}"
      user: "{{ env_var('WAREHOUSE_USER') }}"
      password: "{{ env_var('WAREHOUSE_SECRET') }}"
      port: 5432
      dbname: warehouse
      schema: finance
      threads: 1
      keepalives_idle: 0
      connect_timeout: 10 # default 10 seconds